import { Box, Paper, Stack } from "@mui/material";

interface Expense { amount: number; categoryId: number; }
interface Category { id: number; name: string; }

export default function SpendingInsights({ expenses, categories }: { expenses: Expense[]; categories: Category[] }) {
  const total = expenses.reduce((sum, expense) => sum + expense.amount, 0);
  const bars = expenses.slice(0, 12).reverse();
  const highest = Math.max(...bars.map((expense) => expense.amount), 1);
  const byCategory = categories.map((category) => ({ name: category.name, amount: expenses.filter((expense) => expense.categoryId === category.id).reduce((sum, expense) => sum + expense.amount, 0) })).filter((category) => category.amount > 0);
  return <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", lg: "minmax(0, 1.55fr) minmax(260px, 0.85fr)" }, gap: 1.5 }}><Paper elevation={0} sx={{ minHeight: 292, p: { xs: 2, md: 2.5 }, border: "1px solid var(--color-rule)", borderRadius: "var(--radius-md)" }}><Box component="h2" sx={{ m: 0, color: "var(--color-ink)", fontSize: "var(--text-base)", fontWeight: 800 }}>Expenses overview</Box><Box sx={{ mt: 0.5, color: "var(--color-muted)", fontSize: "var(--text-sm)" }}>{expenses.length ? "Your latest expenses" : "Your spending will appear here."}</Box><Box sx={{ height: 160, mt: 3, display: "flex", alignItems: "end", gap: 1, borderBottom: "1px solid var(--color-rule)" }}>{bars.length ? bars.map((expense, index) => <Box key={index} sx={{ flex: 1, minWidth: 0, height: `${Math.max(10, (expense.amount / highest) * 100)}%`, borderRadius: "6px 6px 0 0", bgcolor: index === bars.length - 1 ? "var(--color-accent)" : "var(--color-accent-soft)" }} />) : <Box sx={{ width: "100%", pb: 2, color: "var(--color-muted)", textAlign: "center", fontSize: "var(--text-sm)" }}>No expenses yet</Box>}</Box></Paper><Paper elevation={0} sx={{ p: { xs: 2, md: 2.5 }, border: "1px solid var(--color-rule)", borderRadius: "var(--radius-md)" }}><Box component="h2" sx={{ m: 0, color: "var(--color-ink)", fontSize: "var(--text-base)", fontWeight: 800 }}>Spending by category</Box><Box sx={{ mt: 0.5, color: "var(--color-muted)", fontSize: "var(--text-sm)" }}>{total ? `${total.toFixed(2)} PLN in total` : "Categories will appear after your first expense."}</Box><Stack spacing={2} sx={{ mt: 3 }}>{byCategory.length ? byCategory.map((category) => <Box key={category.name}><Stack direction="row" sx={{ justifyContent: "space-between" }}><Box sx={{ color: "var(--color-ink-2)", fontSize: "var(--text-sm)", fontWeight: 700 }}>{category.name}</Box><Box sx={{ color: "var(--color-ink)", fontFamily: "var(--font-numeric)", fontSize: "var(--text-sm)", fontWeight: 700 }}>{category.amount.toFixed(2)} PLN</Box></Stack><Box sx={{ height: 7, mt: 0.75, borderRadius: 99, bgcolor: "var(--color-paper-2)" }}><Box sx={{ height: "100%", width: `${(category.amount / total) * 100}%`, borderRadius: 99, bgcolor: "var(--color-accent)" }} /></Box></Box>) : <Box sx={{ display: "grid", placeItems: "center", minHeight: 148, border: "1px dashed var(--color-rule)", borderRadius: "var(--radius-sm)", color: "var(--color-muted)", fontSize: "var(--text-sm)" }}>No categories to show</Box>}</Stack></Paper></Box>;
}
